force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TradeTriggerHandler.cls
public class TradeTriggerHandler {

    /***********************************************************************************************
    * @author       Spyros Michailidis
    * @date         2022-09-04
    * @description  It creates a new chatter post for every trade provided in the parameters
    * @return       (HttpResponse) the mock response
    ************************************************************************************************/
    public static void createChatterPost(List<Trade__c> trades) {
        CollaborationGroup[] groups =  [SELECT Id FROM CollaborationGroup WHERE name = 'Trade reviewers'];
        if(groups.size() != 1) return;
        FeedItem[] posts = new List<FeedItem>();
        for(Trade__c trade : trades) {
            FeedItem post = new FeedItem();
            post.ParentId = groups[0].Id; 
            post.Title = 'Trade ' + trade.Name; 
            post.IsRichText = true; 
            post.Body = '<p>A new trade has been created with the following data:</p>';
            post.Body += '<p>Sell Currency: ' + trade.Sell_Currency__c + '</p>';
            post.Body += '<p>Sell Amount: ' + trade.Sell_Amount__c + '</p>';
            post.Body += '<p>Buy Currency: ' + trade.Buy_Currency__c + '</p>';
            post.Body += '<p>Buy Amount: ' + trade.Buy_Amount__c + '</p>';
            post.Body += '<p>Rate: ' + trade.Rate__c + '</p>';
            post.Body += '<p>Booked Date: ' + trade.CreatedDate + '</p>';
            post.Body += '<p>You may find more details in the link below</p>';
            post.LinkUrl = '/' + trade.Id;
            postS.add(post);
        }
        insert posts;
    }
}