force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TradeTriggerHandler_Test.cls
@isTest(SeeAllData=True)
public class TradeTriggerHandler_Test {


    @isTest
    public static void testCreateChatterPost() {
        CollaborationGroup tradeReviewers = [SELECT Id FROM CollaborationGroup WHERE Name = 'Trade reviewers'];
        Trade__c t1 = new Trade__c();
        t1 = new Trade__c();
        t1.Sell_Currency__c = 'EUR';
        t1.Sell_Amount__c = 5.5;
        t1.Buy_Currency__c = 'USD';
        t1.Buy_Amount__c = 4.6;
        t1.Rate__c = 1.1;
        Trade__c t2 = t1.clone();
        insert new List<Trade__c>{t1,t2};

        FeedItem[] posts = [SELECT Id FROM FeedItem WHERE ParentId =: tradeReviewers.Id];
        System.assertEquals(2, posts.size());
    }
}